use_frameworks!

target 'DividerView_Example' do
  pod 'DividerView', :path => '../'

  target 'DividerView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
