use_frameworks!

target 'DividerView_Example' do
  pod 'DividerView', :path => '../'

  target 'DividerView_Tests' do
    inherit! :search_paths

    pod 'Quick', :git => 'git@github.com:Quick/Quick.git', :branch => 'swift-3.0'
    pod 'Nimble', :git => 'git@github.com:Quick/Nimble.git', :branch => 'swift-3.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
