# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
rvm: 2.2.2
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install xcpretty
before_script:
- cd Example
- pod install --repo-update
script:
- set -o pipefail && xcodebuild test -workspace DividerView.xcworkspace -scheme DividerView-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty
- cd ../
- pod lib lint
